de:
  pageflow_scrolled:
    public:
      sound_disclaimer:
        help_text: Dieser Artikel wirkt am besten mit eingeschaltetem Ton.<br/>
                   Klicken Sie einmal in dieses Feld, um den Ton für die gesamte Geschichte zu aktivieren.
